name: Lint
on:
  push: { branches: [ "development" ] }
  pull_request: { branches: [ "development" ] }

jobs:
  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          sudo apt-get install -y codespell
      - name: Run codespell
        shell: bash -l {0}
        run: codespell --ignore-words=.codespell_ignore M2/Macaulay2/packages

env:
  MAKEFLAGS: -j2
